// generated by datadump-merging

export const gameMapBounds: { x: number[]; y: number[]; } = { x: [-3200,-3200], y: [3200,3200] };
export const gameMapWidthUnits: number = 0;
export const gameMapHeightUnits: number = 0;

export const tileSize: number = 256;
export const unitsPerPixel: number = 128;
export const mapWidthPx: number = 25600;
export const mapHeightPx: number = 25600;
